// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.2
// - protoc             v4.23.1
// source: api/provider/v1/provider.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProviderBaserService = "/provider.v1.Provider/BaserService"

type ProviderHTTPServer interface {
	// BaserService Sends a greeting
	BaserService(context.Context, *Request) (*Response, error)
}

func RegisterProviderHTTPServer(s *http.Server, srv ProviderHTTPServer) {
	r := s.Route("/")
	r.GET("/provider/{event}", _Provider_BaserService0_HTTP_Handler(srv))
}

func _Provider_BaserService0_HTTP_Handler(srv ProviderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Request
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProviderBaserService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BaserService(ctx, req.(*Request))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Response)
		return ctx.Result(200, reply)
	}
}

type ProviderHTTPClient interface {
	BaserService(ctx context.Context, req *Request, opts ...http.CallOption) (rsp *Response, err error)
}

type ProviderHTTPClientImpl struct {
	cc *http.Client
}

func NewProviderHTTPClient(client *http.Client) ProviderHTTPClient {
	return &ProviderHTTPClientImpl{client}
}

func (c *ProviderHTTPClientImpl) BaserService(ctx context.Context, in *Request, opts ...http.CallOption) (*Response, error) {
	var out Response
	pattern := "/provider/{event}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProviderBaserService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
